# Generated by Django 3.2.4 on 2021-06-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210622_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='minutes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='ppm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ppp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ppppm',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_points',
            field=models.IntegerField(default=1),
        ),
    ]
