# Generated by Django 3.2.5 on 2021-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210627_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField()),
                ('finished', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
