# Generated by Django 3.2.5 on 2021-07-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210704_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='ppm',
            new_name='points_per_game',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='ppp',
            new_name='points_per_minute',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='ppppm',
            new_name='points_per_price',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='last_name',
            new_name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='form',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='ict_index',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='points_per_price_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='points_per_price_per_minute',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='takes_corners',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='takes_freekicks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='takes_penalties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='web_name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
