# Generated by Django 3.2.5 on 2021-07-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210704_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField(default=0)),
                ('is_home', models.BooleanField(default=False)),
                ('name_home', models.CharField(default=' ', max_length=100)),
                ('short_name_home', models.CharField(default=' ', max_length=100)),
                ('name_away', models.CharField(default=' ', max_length=100)),
                ('short_name_away', models.CharField(default=' ', max_length=100)),
                ('difficulty', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player')),
            ],
        ),
        migrations.DeleteModel(
            name='Gameweek',
        ),
    ]
