# Generated by Django 3.2.5 on 2021-07-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210709_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('name_h', models.CharField(default=' ', max_length=100)),
                ('short_name_h', models.CharField(default=' ', max_length=100)),
                ('team_h_difficulty', models.IntegerField(default=0)),
                ('name_a', models.CharField(default=' ', max_length=100)),
                ('short_name_a', models.CharField(default=' ', max_length=100)),
                ('team_a_difficulty', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='PlayerFixture',
        ),
    ]
