# Generated by Django 3.2.5 on 2021-07-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210710_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='short_name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
