# Generated by Django 3.2.5 on 2021-07-26 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210726_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameweek',
            old_name='number',
            new_name='id',
        ),
    ]
