# Generated by Django 3.2.5 on 2021-07-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_number_gameweek_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
